Try to deploy to dev domain

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -72,4 +72,14 @@ jobs:
           npx vercel telemetry disable
           npx vercel pull --yes --environment=development --token=$VERCEL_TOKEN
           npx vercel build --token=$VERCEL_TOKEN
-          npx vercel deploy --prebuilt --token=$VERCEL_TOKEN
+          npx vercel deploy --prebuilt --token=$VERCEL_TOKEN >deployment-url.txt 2>error.txt
+          code=$?
+          if [ $code -eq 0 ]; then
+            # Now you can use the deployment url from stdout for the next step of your workflow
+            deploymentUrl=`cat deployment-url.txt`
+            npx vercel alias $deploymentUrl dev.coh3stats.com
+          else
+            # Handle the error
+            errorMessage=`cat error.txt`
+            echo "There was an error: $errorMessage"
+          fi
