Deploy back to Netlify :D

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -54,14 +54,14 @@ jobs:
           environment: ${{ env.EDGIO_ENV }}
           ignore_empty: true
           ignore_missing: true
-      #      - name: Deploy to Netlify hosting
-      #        env:
-      #          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
-      #          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID_DEV}}
-      #          NODE_VERSION: "20.x"
-      #        run: |
-      #          npx netlify --telemetry-disable
-      #          netlify deploy --build --prod
+      - name: Deploy to Netlify hosting
+        env:
+          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
+          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID_DEV}}
+          NODE_VERSION: "20.x"
+        run: |
+          npx netlify --telemetry-disable
+          netlify deploy --build --prod
       #      - name: Deploy to Edgio hosting
       #        env:
       #          DEPLOY_TOKEN: ${{ secrets.EDGIO_V7_DEPLOY_TOKEN}}
@@ -110,23 +110,24 @@ jobs:
       #            errorMessage=`cat error.txt`
       #            echo "There was an error: $errorMessage"
       #          fi
-      - name: Deploy to Vercel hosting - PV org
-        env:
-          VERCEL_TOKEN: ${{secrets.VERCEL_DEPLOY_TOKEN_PV}}
-          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID_PV}}
-          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID_PV}}
-        run: |
-          npx vercel telemetry disable
-          npx vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
-          npx vercel build --token=$VERCEL_TOKEN
-          npx vercel deploy --prebuilt --archive=tgz --token=$VERCEL_TOKEN >deployment-url.txt 2>error.txt
-          code=$?
-          if [ $code -eq 0 ]; then
-            # Now you can use the deployment url from stdout for the next step of your workflow
-            deploymentUrl=`cat deployment-url.txt`
-            npx vercel alias $deploymentUrl dev.coh3stats.com --token=$VERCEL_TOKEN --scope petrveceras-projects
-          else
-            # Handle the error
-            errorMessage=`cat error.txt`
-            echo "There was an error: $errorMessage"
-          fi
+
+#      - name: Deploy to Vercel hosting - PV org
+#        env:
+#          VERCEL_TOKEN: ${{secrets.VERCEL_DEPLOY_TOKEN_PV}}
+#          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID_PV}}
+#          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID_PV}}
+#        run: |
+#          npx vercel telemetry disable
+#          npx vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
+#          npx vercel build --token=$VERCEL_TOKEN
+#          npx vercel deploy --prebuilt --archive=tgz --token=$VERCEL_TOKEN >deployment-url.txt 2>error.txt
+#          code=$?
+#          if [ $code -eq 0 ]; then
+#            # Now you can use the deployment url from stdout for the next step of your workflow
+#            deploymentUrl=`cat deployment-url.txt`
+#            npx vercel alias $deploymentUrl dev.coh3stats.com --token=$VERCEL_TOKEN --scope petrveceras-projects
+#          else
+#            # Handle the error
+#            errorMessage=`cat error.txt`
+#            echo "There was an error: $errorMessage"
+#          fi
