Try prod deploy?

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -90,6 +90,26 @@ jobs:
       #            errorMessage=`cat error.txt`
       #            echo "There was an error: $errorMessage"
       #          fi
+      #      - name: Deploy to Vercel hosting - PV org
+      #        env:
+      #          VERCEL_TOKEN: ${{secrets.VERCEL_DEPLOY_TOKEN_PV}}
+      #          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID_PV}}
+      #          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID_PV}}
+      #        run: |
+      #          npx vercel telemetry disable
+      #          npx vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
+      #          npx vercel build --token=$VERCEL_TOKEN
+      #          npx vercel deploy --prebuilt --token=$VERCEL_TOKEN >deployment-url.txt 2>error.txt
+      #          code=$?
+      #          if [ $code -eq 0 ]; then
+      #            # Now you can use the deployment url from stdout for the next step of your workflow
+      #            deploymentUrl=`cat deployment-url.txt`
+      #            npx vercel alias $deploymentUrl dev.coh3stats.com --token=$VERCEL_TOKEN --scope petrveceras-projects
+      #          else
+      #            # Handle the error
+      #            errorMessage=`cat error.txt`
+      #            echo "There was an error: $errorMessage"
+      #          fi
       - name: Deploy to Vercel hosting - PV org
         env:
           VERCEL_TOKEN: ${{secrets.VERCEL_DEPLOY_TOKEN_PV}}
@@ -97,9 +117,9 @@ jobs:
           VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID_PV}}
         run: |
           npx vercel telemetry disable
-          npx vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
-          npx vercel build --token=$VERCEL_TOKEN
-          npx vercel deploy --prebuilt --token=$VERCEL_TOKEN >deployment-url.txt 2>error.txt
+          npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN
+          npx vercel build --prod --token=$VERCEL_TOKEN
+          npx vercel deploy -prod --prebuilt --token=$VERCEL_TOKEN >deployment-url.txt 2>error.txt
           code=$?
           if [ $code -eq 0 ]; then
             # Now you can use the deployment url from stdout for the next step of your workflow
