Enable vercel deploy

diff --git a/.github/workflows/deploy-prod.yml b/.github/workflows/deploy-prod.yml
--- a/.github/workflows/deploy-prod.yml
+++ b/.github/workflows/deploy-prod.yml
@@ -58,27 +58,27 @@ jobs:
         run: |
           npx netlify --telemetry-disable
           npx netlify deploy --build --prod
-      #
-      #      - name: Deploy to Vercel hosting
-      #        env:
-      #          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
-      #          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
-      #          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
-      #        run: |
-      #          npx vercel telemetry disable
-      #          npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN
-      #          npx vercel build --prod --token=$VERCEL_TOKEN
-      #          npx vercel deploy --prod --prebuilt --archive=tgz --token=$VERCEL_TOKEN >deployment-url.txt 2>error.txt
-      #          code=$?
-      #          if [ $code -eq 0 ]; then
-      #            # Now you can use the deployment url from stdout for the next step of your workflow
-      #            deploymentUrl=`cat deployment-url.txt`
-      #            npx vercel alias $deploymentUrl coh3stats.com --token=$VERCEL_TOKEN --scope cohstats
-      #          else
-      #            # Handle the error
-      #            errorMessage=`cat error.txt`
-      #            echo "There was an error: $errorMessage"
-      #          fi
+
+      - name: Deploy to Vercel hosting
+        env:
+          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
+          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
+          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
+        run: |
+          npx vercel telemetry disable
+          npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN
+          npx vercel build --prod --token=$VERCEL_TOKEN
+          npx vercel deploy --prod --prebuilt --archive=tgz --token=$VERCEL_TOKEN >deployment-url.txt 2>error.txt
+          code=$?
+          if [ $code -eq 0 ]; then
+            # Now you can use the deployment url from stdout for the next step of your workflow
+            deploymentUrl=`cat deployment-url.txt`
+            npx vercel alias $deploymentUrl coh3stats.com --token=$VERCEL_TOKEN --scope cohstats
+          else
+            # Handle the error
+            errorMessage=`cat error.txt`
+            echo "There was an error: $errorMessage"
+          fi
 
 #      - name: Deploy to Vercel hosting - PV org
 #        env:
