Create a preview deployments

diff --git a/.github/workflows/preview.yml b/.github/workflows/preview.yml
--- a/.github/workflows/preview.yml
+++ b/.github/workflows/preview.yml
@@ -5,7 +5,7 @@ on:
       - master
 
 env:
-  EDGIO_ENV: preview
+  DEPLOY_ENV: preview
   BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
   SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN}}
 
@@ -14,7 +14,7 @@ jobs:
     name: Deploy Web Preview
     environment:
       name: preview
-      url: https://coh-stats-coh3-stats-${{ env.BRANCH_NAME }}.alt.free.layer0-perma.link
+      url: https://preview.coh3stats.com
 
     concurrency:
       group: preview-${{ github.ref }}
@@ -53,22 +53,35 @@ jobs:
           SENTRY_ORG: coh-stats
           SENTRY_PROJECT: coh3-stats-web
         with:
-          environment: ${{ env.EDGIO_ENV }}
+          environment: ${{ env.DEPLOY_ENV }}
           ignore_empty: true
           ignore_missing: true
 
       - name: Run the build
         run: yarn build
 
-      - name: Deploy to Edgio hosting
+      - name: Deploy to Vercel hosting
         if: ${{ !startsWith(github.head_ref, 'renovate/') }}
         env:
-          DEPLOY_TOKEN: ${{ secrets.EDGIO_V7_DEPLOY_TOKEN}}
+          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
+          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
+          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
         run: |
-          npx edgio deploy --skip-build --property=coh3-stats --organization=coh-stats --environment=$EDGIO_ENV --token $DEPLOY_TOKEN --branch=$BRANCH_NAME
-          npx edgio cache-clear --property=coh3-stats --organization=coh-stats -e $EDGIO_ENV --token $DEPLOY_TOKEN --path=/
-      - name: Replace Slashes in Branch Name
-        run: echo "LINK_SAFE_BRANCH_NAME=$(echo $BRANCH_NAME | sed 's|/|-|g' | sed 's|\.|-|g')" >> $GITHUB_ENV
+          npx vercel telemetry disable
+          # On vercel, development env is what we used to call preview
+          npx vercel pull --yes --environment=development --token=$VERCEL_TOKEN
+          npx vercel build --token=$VERCEL_TOKEN
+          npx vercel deploy --prebuilt --token=$VERCEL_TOKEN >deployment-url.txt 2>error.txt
+          code=$?
+          if [ $code -eq 0 ]; then
+            # Now you can use the deployment url from stdout for the next step of your workflow
+            echo "DEPLOYMENT_URL=$(cat deployment-url.txt)" >> $GITHUB_ENV
+          else
+            # Handle the error
+            errorMessage=`cat error.txt`
+            echo "There was an error: $errorMessage"
+          fi
+
       - uses: jwalton/gh-find-current-pr@v1
         id: finder
       - name: Publish Preview Link
@@ -79,29 +92,29 @@ jobs:
           header: preview
           message: |
             🌐 Branch deployed as preview to:
-            https://coh-stats-coh3-stats-${{ env.LINK_SAFE_BRANCH_NAME }}.edge.edgio-perma.link
+            ${{ env.DEPLOYMENT_URL }}
 
-  lighthouse:
-    name: Lighthouse report
-    runs-on: ubuntu-latest
-    needs: build-deploy-web
-    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
-    steps:
-      - name: Fireup the preview enviroment with request
-        run: |
-          curl -H 'Content-Type: application/json' -H 'lighthouse: report' https://preview.coh3stats.com
-      - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
-      - name: Lighthouse
-        uses: foo-software/lighthouse-check-action@master
-        with:
-          outputDirectory: ${{ github.workspace }}/tmp/artifacts
-          urls: https://preview.coh3stats.com
-          extraHeaders: '{ "lighthouse": "report" }'
-          prCommentEnabled: true
-          device: all
-          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
-      - name: Upload artifacts
-        uses: actions/upload-artifact@master
-        with:
-          name: Lighthouse reports
-          path: ${{ github.workspace }}/tmp/artifacts
+#  lighthouse:
+#    name: Lighthouse report
+#    runs-on: ubuntu-latest
+#    needs: build-deploy-web
+#    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
+#    steps:
+#      - name: Fireup the preview enviroment with request
+#        run: |
+#          curl -H 'Content-Type: application/json' -H 'lighthouse: report' https://preview.coh3stats.com
+#      - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
+#      - name: Lighthouse
+#        uses: foo-software/lighthouse-check-action@master
+#        with:
+#          outputDirectory: ${{ github.workspace }}/tmp/artifacts
+#          urls: https://preview.coh3stats.com
+#          extraHeaders: '{ "lighthouse": "report" }'
+#          prCommentEnabled: true
+#          device: all
+#          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
+#      - name: Upload artifacts
+#        uses: actions/upload-artifact@master
+#        with:
+#          name: Lighthouse reports
+#          path: ${{ github.workspace }}/tmp/artifacts
